# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Configure.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Configure(object):
    def setupUi(self, Configure):
        Configure.setObjectName(_fromUtf8("Configure"))
        Configure.resize(529, 380)
        self.tabWidget = QtGui.QTabWidget(Configure)
        self.tabWidget.setGeometry(QtCore.QRect(40, 10, 451, 291))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 10, 300, 230))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.MenDWLdoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.MenDWLdoubleSpinBox.setObjectName(_fromUtf8("MenDWLdoubleSpinBox"))
        self.horizontalLayout.addWidget(self.MenDWLdoubleSpinBox)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.horizontalLayout_22.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.MenCWLdoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.MenCWLdoubleSpinBox.setObjectName(_fromUtf8("MenCWLdoubleSpinBox"))
        self.horizontalLayout_2.addWidget(self.MenCWLdoubleSpinBox)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_43 = QtGui.QLabel(self.layoutWidget)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_5.addWidget(self.label_43)
        self.MenDWLerrordoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.MenDWLerrordoubleSpinBox.setObjectName(_fromUtf8("MenDWLerrordoubleSpinBox"))
        self.horizontalLayout_5.addWidget(self.MenDWLerrordoubleSpinBox)
        self.label_44 = QtGui.QLabel(self.layoutWidget)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_5.addWidget(self.label_44)
        self.MenCWLerrordoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.MenCWLerrordoubleSpinBox.setObjectName(_fromUtf8("MenCWLerrordoubleSpinBox"))
        self.horizontalLayout_5.addWidget(self.MenCWLerrordoubleSpinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.BoatDWLdoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.BoatDWLdoubleSpinBox.setObjectName(_fromUtf8("BoatDWLdoubleSpinBox"))
        self.horizontalLayout_3.addWidget(self.BoatDWLdoubleSpinBox)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.BoatCWLdoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.BoatCWLdoubleSpinBox.setObjectName(_fromUtf8("BoatCWLdoubleSpinBox"))
        self.horizontalLayout_4.addWidget(self.BoatCWLdoubleSpinBox)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_45 = QtGui.QLabel(self.layoutWidget)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_20.addWidget(self.label_45)
        self.BoatDWLerrordoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.BoatDWLerrordoubleSpinBox.setObjectName(_fromUtf8("BoatDWLerrordoubleSpinBox"))
        self.horizontalLayout_20.addWidget(self.BoatDWLerrordoubleSpinBox)
        self.label_46 = QtGui.QLabel(self.layoutWidget)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_20.addWidget(self.label_46)
        self.BoatCWLerrordoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.BoatCWLerrordoubleSpinBox.setObjectName(_fromUtf8("BoatCWLerrordoubleSpinBox"))
        self.horizontalLayout_20.addWidget(self.BoatCWLerrordoubleSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_5.addWidget(self.label_11)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_21.addWidget(self.label_12)
        self.Boat2DWLdoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.Boat2DWLdoubleSpinBox.setObjectName(_fromUtf8("Boat2DWLdoubleSpinBox"))
        self.horizontalLayout_21.addWidget(self.Boat2DWLdoubleSpinBox)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_21.addWidget(self.label_13)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_6.addWidget(self.label_14)
        self.Boat2CWLdoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.Boat2CWLdoubleSpinBox.setObjectName(_fromUtf8("Boat2CWLdoubleSpinBox"))
        self.horizontalLayout_6.addWidget(self.Boat2CWLdoubleSpinBox)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_6.addWidget(self.label_15)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_47 = QtGui.QLabel(self.layoutWidget)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_19.addWidget(self.label_47)
        self.Boat2DWLerrordoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.Boat2DWLerrordoubleSpinBox.setObjectName(_fromUtf8("Boat2DWLerrordoubleSpinBox"))
        self.horizontalLayout_19.addWidget(self.Boat2DWLerrordoubleSpinBox)
        self.label_48 = QtGui.QLabel(self.layoutWidget)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_19.addWidget(self.label_48)
        self.Boat2CWLerrordoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.Boat2CWLerrordoubleSpinBox.setObjectName(_fromUtf8("Boat2CWLerrordoubleSpinBox"))
        self.horizontalLayout_19.addWidget(self.Boat2CWLerrordoubleSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(55, 22, 211, 131))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_16 = QtGui.QLabel(self.layoutWidget1)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.label_19 = QtGui.QLabel(self.layoutWidget1)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_7.addWidget(self.label_19)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_17 = QtGui.QLabel(self.layoutWidget1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_8.addWidget(self.label_17)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        self.label_20 = QtGui.QLabel(self.layoutWidget1)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_8.addWidget(self.label_20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_18 = QtGui.QLabel(self.layoutWidget1)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_9.addWidget(self.label_18)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_9.addWidget(self.lineEdit_3)
        self.label_21 = QtGui.QLabel(self.layoutWidget1)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_9.addWidget(self.label_21)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.widget = QtGui.QWidget(Configure)
        self.widget.setGeometry(QtCore.QRect(330, 320, 158, 25))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.OKbutton = QtGui.QPushButton(self.widget)
        self.OKbutton.setObjectName(_fromUtf8("OKbutton"))
        self.horizontalLayout_10.addWidget(self.OKbutton)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_10.addWidget(self.buttonBox)

        self.retranslateUi(Configure)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Configure.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Configure.reject)
        QtCore.QMetaObject.connectSlotsByName(Configure)

    def retranslateUi(self, Configure):
        Configure.setWindowTitle(_translate("Configure", "配置", None))
        self.label_5.setText(_translate("Configure", "人员：", None))
        self.label.setText(_translate("Configure", "DWL风压率：", None))
        self.label_3.setText(_translate("Configure", "%", None))
        self.label_2.setText(_translate("Configure", "CWL风压率：", None))
        self.label_4.setText(_translate("Configure", "%", None))
        self.label_43.setText(_translate("Configure", "DWL误差：", None))
        self.label_44.setText(_translate("Configure", "CWL误差：", None))
        self.label_6.setText(_translate("Configure", "救生艇：", None))
        self.label_7.setText(_translate("Configure", "DWL风压率：", None))
        self.label_8.setText(_translate("Configure", "%", None))
        self.label_9.setText(_translate("Configure", "CWL风压率：", None))
        self.label_10.setText(_translate("Configure", "%", None))
        self.label_45.setText(_translate("Configure", "DWL误差：", None))
        self.label_46.setText(_translate("Configure", "CWL误差：", None))
        self.label_11.setText(_translate("Configure", "船舶：", None))
        self.label_12.setText(_translate("Configure", "DWL风压率：", None))
        self.label_13.setText(_translate("Configure", "%", None))
        self.label_14.setText(_translate("Configure", "CWL风压率：", None))
        self.label_15.setText(_translate("Configure", "%", None))
        self.label_47.setText(_translate("Configure", "DWL误差：", None))
        self.label_48.setText(_translate("Configure", "CWL误差：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Configure", "参数配置", None))
        self.label_16.setText(_translate("Configure", "飞机起降距离：", None))
        self.label_19.setText(_translate("Configure", "m", None))
        self.label_17.setText(_translate("Configure", "飞机起降宽度：", None))
        self.label_20.setText(_translate("Configure", "m", None))
        self.label_18.setText(_translate("Configure", "起降安全距离：", None))
        self.label_21.setText(_translate("Configure", "m", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Configure", "起飞降落准则", None))
        self.OKbutton.setText(_translate("Configure", "OK", None))

