# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WaterRescue(object):
    def setupUi(self, WaterRescue):
        WaterRescue.setObjectName(_fromUtf8("WaterRescue"))
        WaterRescue.setWindowModality(QtCore.Qt.NonModal)
        WaterRescue.resize(1140, 784)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/新前缀/resource/boat_128px_1189224_easyicon.net.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WaterRescue.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(WaterRescue)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.radioButton = QtGui.QRadioButton(self.frame)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_8.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.frame)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout_8.addWidget(self.radioButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.WaterSpeedLabel = QtGui.QLabel(self.frame)
        self.WaterSpeedLabel.setObjectName(_fromUtf8("WaterSpeedLabel"))
        self.horizontalLayout_4.addWidget(self.WaterSpeedLabel)
        self.SeaSpeeddoubleSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.SeaSpeeddoubleSpinBox.setMaximum(100000.0)
        self.SeaSpeeddoubleSpinBox.setObjectName(_fromUtf8("SeaSpeeddoubleSpinBox"))
        self.horizontalLayout_4.addWidget(self.SeaSpeeddoubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.WaterDirectionLabel_2 = QtGui.QLabel(self.frame)
        self.WaterDirectionLabel_2.setObjectName(_fromUtf8("WaterDirectionLabel_2"))
        self.horizontalLayout_6.addWidget(self.WaterDirectionLabel_2)
        self.SeaAngledoubleSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.SeaAngledoubleSpinBox.setMaximum(90.0)
        self.SeaAngledoubleSpinBox.setObjectName(_fromUtf8("SeaAngledoubleSpinBox"))
        self.horizontalLayout_6.addWidget(self.SeaAngledoubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.TrendSpeedLabel_5 = QtGui.QLabel(self.frame)
        self.TrendSpeedLabel_5.setObjectName(_fromUtf8("TrendSpeedLabel_5"))
        self.horizontalLayout_16.addWidget(self.TrendSpeedLabel_5)
        self.TrendSpeeddoubleSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.TrendSpeeddoubleSpinBox.setMaximum(100000.0)
        self.TrendSpeeddoubleSpinBox.setObjectName(_fromUtf8("TrendSpeeddoubleSpinBox"))
        self.horizontalLayout_16.addWidget(self.TrendSpeeddoubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.WaterDirectionLabel_6 = QtGui.QLabel(self.frame)
        self.WaterDirectionLabel_6.setObjectName(_fromUtf8("WaterDirectionLabel_6"))
        self.horizontalLayout_17.addWidget(self.WaterDirectionLabel_6)
        self.TrendAngledoubleSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.TrendAngledoubleSpinBox.setMaximum(90.0)
        self.TrendAngledoubleSpinBox.setObjectName(_fromUtf8("TrendAngledoubleSpinBox"))
        self.horizontalLayout_17.addWidget(self.TrendAngledoubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.WindSpeedLabel = QtGui.QLabel(self.frame)
        self.WindSpeedLabel.setObjectName(_fromUtf8("WindSpeedLabel"))
        self.horizontalLayout_7.addWidget(self.WindSpeedLabel)
        self.WindSpeeddoubleSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.WindSpeeddoubleSpinBox.setMaximum(100000.0)
        self.WindSpeeddoubleSpinBox.setObjectName(_fromUtf8("WindSpeeddoubleSpinBox"))
        self.horizontalLayout_7.addWidget(self.WindSpeeddoubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.WaterDirectionLabel_3 = QtGui.QLabel(self.frame)
        self.WaterDirectionLabel_3.setObjectName(_fromUtf8("WaterDirectionLabel_3"))
        self.horizontalLayout_9.addWidget(self.WaterDirectionLabel_3)
        self.WindAngledoubleSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.WindAngledoubleSpinBox.setMaximum(90.0)
        self.WindAngledoubleSpinBox.setObjectName(_fromUtf8("WindAngledoubleSpinBox"))
        self.horizontalLayout_9.addWidget(self.WindAngledoubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayout_8.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MenpushButton = QtGui.QPushButton(self.frame_3)
        self.MenpushButton.setObjectName(_fromUtf8("MenpushButton"))
        self.gridLayout.addWidget(self.MenpushButton, 0, 0, 1, 1)
        self.BoatpushButton = QtGui.QPushButton(self.frame_3)
        self.BoatpushButton.setObjectName(_fromUtf8("BoatpushButton"))
        self.gridLayout.addWidget(self.BoatpushButton, 0, 1, 1, 1)
        self.BoatpushButton_2 = QtGui.QPushButton(self.frame_3)
        self.BoatpushButton_2.setObjectName(_fromUtf8("BoatpushButton_2"))
        self.gridLayout.addWidget(self.BoatpushButton_2, 1, 0, 1, 2)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.verticalLayout_3.addWidget(self.dateTimeEdit)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.TimespinBox_1 = QtGui.QSpinBox(self.centralwidget)
        self.TimespinBox_1.setObjectName(_fromUtf8("TimespinBox_1"))
        self.horizontalLayout_10.addWidget(self.TimespinBox_1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.TimespinBox_2 = QtGui.QSpinBox(self.centralwidget)
        self.TimespinBox_2.setObjectName(_fromUtf8("TimespinBox_2"))
        self.horizontalLayout_10.addWidget(self.TimespinBox_2)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.TimespinBox_3 = QtGui.QSpinBox(self.centralwidget)
        self.TimespinBox_3.setObjectName(_fromUtf8("TimespinBox_3"))
        self.horizontalLayout_10.addWidget(self.TimespinBox_3)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.FigurepushButton = QtGui.QPushButton(self.frame_2)
        self.FigurepushButton.setObjectName(_fromUtf8("FigurepushButton"))
        self.verticalLayout.addWidget(self.FigurepushButton)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.LocationtextEdit = QtGui.QTextEdit(self.frame_2)
        self.LocationtextEdit.setMaximumSize(QtCore.QSize(120, 25))
        self.LocationtextEdit.setObjectName(_fromUtf8("LocationtextEdit"))
        self.horizontalLayout_2.addWidget(self.LocationtextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.TwoDpushButton = QtGui.QPushButton(self.centralwidget)
        self.TwoDpushButton.setObjectName(_fromUtf8("TwoDpushButton"))
        self.horizontalLayout.addWidget(self.TwoDpushButton)
        self.TreeDpushButton = QtGui.QPushButton(self.centralwidget)
        self.TreeDpushButton.setObjectName(_fromUtf8("TreeDpushButton"))
        self.horizontalLayout.addWidget(self.TreeDpushButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 1)
        self.verticalLayout_8.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.FirstpushButton = QtGui.QPushButton(self.centralwidget)
        self.FirstpushButton.setObjectName(_fromUtf8("FirstpushButton"))
        self.horizontalLayout_3.addWidget(self.FirstpushButton)
        self.LastpushButton = QtGui.QPushButton(self.centralwidget)
        self.LastpushButton.setObjectName(_fromUtf8("LastpushButton"))
        self.horizontalLayout_3.addWidget(self.LastpushButton)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.line.raise_()
        WaterRescue.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(WaterRescue)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.FileMenu = QtGui.QMenu(self.menubar)
        self.FileMenu.setObjectName(_fromUtf8("FileMenu"))
        self.EditMenu = QtGui.QMenu(self.menubar)
        self.EditMenu.setObjectName(_fromUtf8("EditMenu"))
        self.HelpMenu = QtGui.QMenu(self.menubar)
        self.HelpMenu.setObjectName(_fromUtf8("HelpMenu"))
        self.SimulationMenu = QtGui.QMenu(self.menubar)
        self.SimulationMenu.setObjectName(_fromUtf8("SimulationMenu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        WaterRescue.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(WaterRescue)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        WaterRescue.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(WaterRescue)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        WaterRescue.setStatusBar(self.statusBar)
        self.FileOpen = QtGui.QAction(WaterRescue)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_d9vcchetbfkcsor/打开_1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileOpen.setIcon(icon1)
        self.FileOpen.setObjectName(_fromUtf8("FileOpen"))
        self.FileQuit = QtGui.QAction(WaterRescue)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/resource/filequit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileQuit.setIcon(icon2)
        self.FileQuit.setShortcut(_fromUtf8(""))
        self.FileQuit.setObjectName(_fromUtf8("FileQuit"))
        self.FileNew = QtGui.QAction(WaterRescue)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/新建.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileNew.setIcon(icon3)
        self.FileNew.setObjectName(_fromUtf8("FileNew"))
        self.FileSaveAs = QtGui.QAction(WaterRescue)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_d9vcchetbfkcsor/另存.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileSaveAs.setIcon(icon4)
        self.FileSaveAs.setObjectName(_fromUtf8("FileSaveAs"))
        self.reset = QtGui.QAction(WaterRescue)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/重置.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset.setIcon(icon5)
        self.reset.setObjectName(_fromUtf8("reset"))
        self.undo = QtGui.QAction(WaterRescue)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/撤销.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo.setIcon(icon6)
        self.undo.setObjectName(_fromUtf8("undo"))
        self.redo = QtGui.QAction(WaterRescue)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/撤销_1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redo.setIcon(icon7)
        self.redo.setObjectName(_fromUtf8("redo"))
        self.Introduce = QtGui.QAction(WaterRescue)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/新前缀/resource/help_info_128px_1172051_easyicon.net.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Introduce.setIcon(icon8)
        self.Introduce.setObjectName(_fromUtf8("Introduce"))
        self.Helper = QtGui.QAction(WaterRescue)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/新前缀/resource/circle_help_128px_1189326_easyicon.net.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Helper.setIcon(icon9)
        self.Helper.setObjectName(_fromUtf8("Helper"))
        self.FileSave = QtGui.QAction(WaterRescue)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/保存.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileSave.setIcon(icon10)
        self.FileSave.setObjectName(_fromUtf8("FileSave"))
        self.boat = QtGui.QAction(WaterRescue)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/救生圈.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boat.setIcon(icon11)
        self.boat.setObjectName(_fromUtf8("boat"))
        self.needsaver = QtGui.QAction(WaterRescue)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/人员.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.needsaver.setIcon(icon12)
        self.needsaver.setObjectName(_fromUtf8("needsaver"))
        self.filedefault = QtGui.QAction(WaterRescue)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/新前缀/resource/default_icon_256px_1114588_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filedefault.setIcon(icon13)
        self.filedefault.setObjectName(_fromUtf8("filedefault"))
        self.start = QtGui.QAction(WaterRescue)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/播放器播放.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon14)
        self.start.setObjectName(_fromUtf8("start"))
        self.pause = QtGui.QAction(WaterRescue)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/播放器_暂停.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon15)
        self.pause.setObjectName(_fromUtf8("pause"))
        self.stop = QtGui.QAction(WaterRescue)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/停止.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon16)
        self.stop.setObjectName(_fromUtf8("stop"))
        self.speed = QtGui.QAction(WaterRescue)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/快进.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.speed.setIcon(icon17)
        self.speed.setObjectName(_fromUtf8("speed"))
        self.slow = QtGui.QAction(WaterRescue)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon_1jx48f4me37vte29/快退.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slow.setIcon(icon18)
        self.slow.setObjectName(_fromUtf8("slow"))
        self.action = QtGui.QAction(WaterRescue)
        self.action.setObjectName(_fromUtf8("action"))
        self.FileMenu.addAction(self.FileNew)
        self.FileMenu.addAction(self.FileOpen)
        self.FileMenu.addAction(self.FileSave)
        self.FileMenu.addAction(self.FileSaveAs)
        self.FileMenu.addSeparator()
        self.FileMenu.addAction(self.filedefault)
        self.FileMenu.addSeparator()
        self.FileMenu.addAction(self.FileQuit)
        self.EditMenu.addAction(self.undo)
        self.EditMenu.addAction(self.redo)
        self.EditMenu.addAction(self.reset)
        self.EditMenu.addSeparator()
        self.HelpMenu.addAction(self.Introduce)
        self.HelpMenu.addSeparator()
        self.HelpMenu.addAction(self.Helper)
        self.SimulationMenu.addAction(self.start)
        self.SimulationMenu.addAction(self.action)
        self.menu_2.addAction(self.boat)
        self.menu_2.addAction(self.needsaver)
        self.menubar.addAction(self.FileMenu.menuAction())
        self.menubar.addAction(self.EditMenu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.SimulationMenu.menuAction())
        self.menubar.addAction(self.HelpMenu.menuAction())
        self.toolBar.addAction(self.FileNew)
        self.toolBar.addAction(self.FileOpen)
        self.toolBar.addAction(self.FileSave)
        self.toolBar.addAction(self.FileSaveAs)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.undo)
        self.toolBar.addAction(self.redo)
        self.toolBar.addAction(self.reset)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.needsaver)
        self.toolBar.addAction(self.boat)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.start)
        self.toolBar.addAction(self.pause)
        self.toolBar.addAction(self.stop)
        self.toolBar.addAction(self.speed)
        self.toolBar.addAction(self.slow)

        self.retranslateUi(WaterRescue)
        QtCore.QMetaObject.connectSlotsByName(WaterRescue)

    def retranslateUi(self, WaterRescue):
        WaterRescue.setWindowTitle(_translate("WaterRescue", "大型水陆两栖飞机着水救援安全性仿真软件", None))
        self.label_6.setText(_translate("WaterRescue", "环境参数：", None))
        self.radioButton.setText(_translate("WaterRescue", "近海", None))
        self.radioButton_2.setText(_translate("WaterRescue", "远海", None))
        self.WaterSpeedLabel.setText(_translate("WaterRescue", "洋流速度：", None))
        self.SeaSpeeddoubleSpinBox.setStatusTip(_translate("WaterRescue", "洋流速度", None))
        self.SeaSpeeddoubleSpinBox.setSuffix(_translate("WaterRescue", "km/h", None))
        self.WaterDirectionLabel_2.setText(_translate("WaterRescue", "洋流方向：", None))
        self.SeaAngledoubleSpinBox.setStatusTip(_translate("WaterRescue", "洋流方向", None))
        self.SeaAngledoubleSpinBox.setSuffix(_translate("WaterRescue", "°", None))
        self.label.setText(_translate("WaterRescue", "以正北为0°，顺时针为正", None))
        self.TrendSpeedLabel_5.setText(_translate("WaterRescue", "潮流速度：", None))
        self.TrendSpeeddoubleSpinBox.setStatusTip(_translate("WaterRescue", "海风速度", None))
        self.TrendSpeeddoubleSpinBox.setSuffix(_translate("WaterRescue", "km/h", None))
        self.WaterDirectionLabel_6.setText(_translate("WaterRescue", "潮流方向：", None))
        self.TrendAngledoubleSpinBox.setStatusTip(_translate("WaterRescue", "海风方向", None))
        self.TrendAngledoubleSpinBox.setSuffix(_translate("WaterRescue", "°", None))
        self.label_7.setText(_translate("WaterRescue", "以正北为0°，顺时针为正", None))
        self.WindSpeedLabel.setText(_translate("WaterRescue", "海风速度：", None))
        self.WindSpeeddoubleSpinBox.setStatusTip(_translate("WaterRescue", "海风速度", None))
        self.WindSpeeddoubleSpinBox.setSuffix(_translate("WaterRescue", "km/h", None))
        self.WaterDirectionLabel_3.setText(_translate("WaterRescue", "海风方向：", None))
        self.WindAngledoubleSpinBox.setStatusTip(_translate("WaterRescue", "海风方向", None))
        self.WindAngledoubleSpinBox.setSuffix(_translate("WaterRescue", "°", None))
        self.label_3.setText(_translate("WaterRescue", "以正北为0°，顺时针为正", None))
        self.label_2.setText(_translate("WaterRescue", "漂移物体编辑：", None))
        self.MenpushButton.setText(_translate("WaterRescue", "人员", None))
        self.BoatpushButton.setText(_translate("WaterRescue", "救生艇", None))
        self.BoatpushButton_2.setText(_translate("WaterRescue", "船舶", None))
        self.label_9.setText(_translate("WaterRescue", "遇难时间：", None))
        self.label_4.setText(_translate("WaterRescue", "预计救援时间：", None))
        self.label_8.setText(_translate("WaterRescue", "小时", None))
        self.label_10.setText(_translate("WaterRescue", "分", None))
        self.label_11.setText(_translate("WaterRescue", "秒", None))
        self.FigurepushButton.setText(_translate("WaterRescue", "计算降落点", None))
        self.label_5.setText(_translate("WaterRescue", "最佳降落点：", None))
        self.TwoDpushButton.setText(_translate("WaterRescue", "二维仿真", None))
        self.TreeDpushButton.setStatusTip(_translate("WaterRescue", "动画仿真", None))
        self.TreeDpushButton.setWhatsThis(_translate("WaterRescue", "动画仿真", None))
        self.TreeDpushButton.setText(_translate("WaterRescue", "动画仿真", None))
        self.FirstpushButton.setText(_translate("WaterRescue", "初始状态", None))
        self.LastpushButton.setText(_translate("WaterRescue", "末状态", None))
        self.pushButton.setText(_translate("WaterRescue", "遇难位置", None))
        self.FileMenu.setTitle(_translate("WaterRescue", "文件(&F)", None))
        self.EditMenu.setTitle(_translate("WaterRescue", "编辑(&E)", None))
        self.HelpMenu.setTitle(_translate("WaterRescue", "帮助(&H)", None))
        self.SimulationMenu.setTitle(_translate("WaterRescue", "仿真(&S)", None))
        self.menu_2.setTitle(_translate("WaterRescue", "模型(m)", None))
        self.toolBar.setWindowTitle(_translate("WaterRescue", "toolBar", None))
        self.FileOpen.setText(_translate("WaterRescue", "打开(&O)", None))
        self.FileOpen.setStatusTip(_translate("WaterRescue", "打开(O)", None))
        self.FileOpen.setShortcut(_translate("WaterRescue", "Ctrl+O", None))
        self.FileQuit.setText(_translate("WaterRescue", "退出(&Q)", None))
        self.FileNew.setText(_translate("WaterRescue", "新建(&N)", None))
        self.FileNew.setStatusTip(_translate("WaterRescue", "新建(N)", None))
        self.FileNew.setShortcut(_translate("WaterRescue", "Ctrl+N", None))
        self.FileSaveAs.setText(_translate("WaterRescue", "另存(&A)", None))
        self.FileSaveAs.setStatusTip(_translate("WaterRescue", "另存(A)", None))
        self.FileSaveAs.setShortcut(_translate("WaterRescue", "Ctrl+Shift+S", None))
        self.reset.setText(_translate("WaterRescue", "重置数据", None))
        self.undo.setText(_translate("WaterRescue", "撤销 ", None))
        self.undo.setStatusTip(_translate("WaterRescue", "撤销", None))
        self.undo.setShortcut(_translate("WaterRescue", "Ctrl+Z", None))
        self.redo.setText(_translate("WaterRescue", "恢复", None))
        self.redo.setStatusTip(_translate("WaterRescue", "恢复", None))
        self.redo.setShortcut(_translate("WaterRescue", "Ctrl+Y", None))
        self.Introduce.setText(_translate("WaterRescue", "软件简介", None))
        self.Helper.setText(_translate("WaterRescue", "功能帮助", None))
        self.Helper.setShortcut(_translate("WaterRescue", "Ctrl+/", None))
        self.FileSave.setText(_translate("WaterRescue", "保存(&S)", None))
        self.FileSave.setStatusTip(_translate("WaterRescue", "保存(S)", None))
        self.FileSave.setShortcut(_translate("WaterRescue", "Ctrl+S", None))
        self.boat.setText(_translate("WaterRescue", "添加救生艇", None))
        self.needsaver.setText(_translate("WaterRescue", "添加待救人员", None))
        self.filedefault.setText(_translate("WaterRescue", "配置", None))
        self.filedefault.setStatusTip(_translate("WaterRescue", "配置", None))
        self.start.setText(_translate("WaterRescue", "二维仿真", None))
        self.start.setToolTip(_translate("WaterRescue", "二维仿真", None))
        self.pause.setText(_translate("WaterRescue", "暂停", None))
        self.stop.setText(_translate("WaterRescue", "停止", None))
        self.speed.setText(_translate("WaterRescue", "快进", None))
        self.slow.setText(_translate("WaterRescue", "快退", None))
        self.action.setText(_translate("WaterRescue", "动画仿真", None))

import tubiao_rc
